// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240903235552_IntialMigration")]
    partial class IntialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.PlayerModels.ElementTypes", b =>
                {
                    b.Property<int>("ElementTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ElementTypeId");

                    b.ToTable("ElementTypes", (string)null);
                });

            modelBuilder.Entity("Api.Models.PlayerModels.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("ChancePlayingNextRound")
                        .HasColumnType("int");

                    b.Property<int?>("ChancePlayingThisRound")
                        .HasColumnType("int");

                    b.Property<int>("ElementTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("News")
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("NewsAdded")
                        .HasColumnType("datetime");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SquadNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("WebName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlayerId");

                    b.HasIndex("ElementTypeId");

                    b.HasIndex("TeamId");

                    b.HasIndex("FirstName", "SecondName")
                        .HasDatabaseName("idx_player_firstname_secondname");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Api.Models.PlayerModels.PlayerPerformance", b =>
                {
                    b.Property<int>("PlayerPerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerPerformanceId"));

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<int>("BonusPointsSystem")
                        .HasColumnType("int");

                    b.Property<int>("CleanSheets")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DreamTeamCount")
                        .HasColumnType("int");

                    b.Property<int>("EventPoints")
                        .HasColumnType("int");

                    b.Property<int>("GoalsConceded")
                        .HasColumnType("int");

                    b.Property<int>("GoalsScored")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<int>("OwnGoals")
                        .HasColumnType("int");

                    b.Property<int>("PenaltiesMissed")
                        .HasColumnType("int");

                    b.Property<int>("PenaltiesSaved")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.Property<int>("Saves")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("PlayerPerformanceId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CreatedAt");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("idx_player_performance_player");

                    b.ToTable("PlayersPerformance", (string)null);
                });

            modelBuilder.Entity("Api.Models.PlayerModels.PlayerStatistics", b =>
                {
                    b.Property<int>("PlayerStatisticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerStatisticsId"));

                    b.Property<decimal>("CleanSheetsPer90")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Creativity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ExpectedAssists")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ExpectedAssistsPer90")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ExpectedGoalInvolvements")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ExpectedGoalInvolvementsPer90")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ExpectedGoals")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ExpectedGoalsConceded")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ExpectedGoalsConcededPer90")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ExpectedGoalsPer90")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("GoalsConcededPer90")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("IctIndex")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("Influence")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("StartsPer90")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Threat")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("PlayerStatisticsId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CreatedAt");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("idx_player_statistics_player");

                    b.ToTable("PlayersStatistics", (string)null);
                });

            modelBuilder.Entity("Api.Models.PlayerModels.PlayerTransfer", b =>
                {
                    b.Property<int>("PlayerTransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerTransferId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TransfersIn")
                        .HasColumnType("int");

                    b.Property<int>("TransfersInEvent")
                        .HasColumnType("int");

                    b.Property<int>("TransfersOut")
                        .HasColumnType("int");

                    b.Property<int>("TransfersOutEvent")
                        .HasColumnType("int");

                    b.HasKey("PlayerTransferId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CreatedAt");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("idx_player_transfer_player");

                    b.ToTable("PlayersTransfer", (string)null);
                });

            modelBuilder.Entity("Api.Models.PlayerModels.PlayerValue", b =>
                {
                    b.Property<int>("PlayerValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerValueId"));

                    b.Property<int>("CostChangeEvent")
                        .HasColumnType("int");

                    b.Property<int>("CostChangeStart")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("NowCost")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("SelectedByPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ValueForm")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ValueSeason")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("PlayerValueId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CreatedAt");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("idx_player_value_player");

                    b.ToTable("PlayersValues", (string)null);
                });

            modelBuilder.Entity("Api.Models.TeamModels.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("strength_attack_away")
                        .HasColumnType("int");

                    b.Property<int>("strength_attack_home")
                        .HasColumnType("int");

                    b.Property<int>("strength_defence_away")
                        .HasColumnType("int");

                    b.Property<int>("strength_defence_home")
                        .HasColumnType("int");

                    b.Property<int>("strength_overall_away")
                        .HasColumnType("int");

                    b.Property<int>("strength_overall_home")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("Api.Models.PlayerModels.Player", b =>
                {
                    b.HasOne("Api.Models.PlayerModels.ElementTypes", "elementType")
                        .WithMany("Players")
                        .HasForeignKey("ElementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.TeamModels.Team", "team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("elementType");

                    b.Navigation("team");
                });

            modelBuilder.Entity("Api.Models.PlayerModels.PlayerPerformance", b =>
                {
                    b.HasOne("Api.Models.PlayerModels.Player", "player")
                        .WithMany("PlayerPerformances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("player");
                });

            modelBuilder.Entity("Api.Models.PlayerModels.PlayerStatistics", b =>
                {
                    b.HasOne("Api.Models.PlayerModels.Player", "player")
                        .WithMany("PlayerStatistics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("player");
                });

            modelBuilder.Entity("Api.Models.PlayerModels.PlayerTransfer", b =>
                {
                    b.HasOne("Api.Models.PlayerModels.Player", "player")
                        .WithMany("PlayerTransfers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("player");
                });

            modelBuilder.Entity("Api.Models.PlayerModels.PlayerValue", b =>
                {
                    b.HasOne("Api.Models.PlayerModels.Player", "player")
                        .WithMany("PlayerValues")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("player");
                });

            modelBuilder.Entity("Api.Models.PlayerModels.ElementTypes", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Api.Models.PlayerModels.Player", b =>
                {
                    b.Navigation("PlayerPerformances");

                    b.Navigation("PlayerStatistics");

                    b.Navigation("PlayerTransfers");

                    b.Navigation("PlayerValues");
                });

            modelBuilder.Entity("Api.Models.TeamModels.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
